[default_session]
startup_command = "l"

[[session]]
name = "Code ğŸ’»"
path = "~/Code"
startup_command = "l"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "niri config"
path = "~/.config/niri"
startup_command = "nvim config.kdl"

[[session]]
name = "neovim config"
path = "~/.config/nvim"
startup_command = "vis"

[[session]]
name = "Scripts ğŸ“œ"
path = "~/.scripts"

[[session]]
name = "pumpndump ğŸ§´"
path = "~/Other/pumpndump"
startup_command = "git status"

[[session]]
name = "portage config ğŸ§´"
path = "~/Other/pumpndump/root/etc/portage/"
startup_command = "l"

[[session]]
name = "tmux config"
path = "~/.tmux"
startup_command = "nvim ~/.tmux.conf"

[[session]]
name = "Notes ğŸ“"
path = "~/Notes"
startup_command = "nvim index.org"

# [[session]]
# name = "Downloads ğŸ“¥"
# path = "~/Downloads"
# startup_command = "jo"

[[session]]
# TODO: update the name fo the session to "update done âœ…" when the u script ends
name = "Update" 
startup_command = "updatescript"
# TODO: implement "detatched feature"
# detached = true # never attach to this session, just create it in the background


[[session]]
# name = "coollittlewebsite"
path = "~/Code/coollittlewebsite"
startup_script = "~/.config/sesh/scripts/coollittlewebsite.sh"
