[default_session]
startup_command = "l"

[[session]]
name = "Code ğŸ’»"
path = "~/Code"
startup_command = "l"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "neovim config"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "Scripts ğŸ“œ"
path = "~/.scripts"

[[session]]
name = "pumpndump ğŸ§´"
path = "~/.pumpfiles"
startup_command = "git status"

[[session]]
name = "portage config ğŸ§´"
path = "~/.pumpfiles/root/etc/portage/"
startup_command = "l"

[[session]]
name = "tmux config"
path = "~/.tmux"
startup_command = "nvim ~/.tmux.conf"

[[session]]
name = "Notes ğŸ“"
path = "~/Notes"
startup_command = "nvim index.org"

[[session]]
name = "Update" 
startup_command = "updatescript"

[[session]]
name = "soosh"
startup_command = "ssh gravity@clr"

[[session]]
path = "~/Code/coollittlewebsite"
startup_script = "~/.config/sesh/scripts/coollittlewebsite.sh"
