[default_session]
startup_command = "l"

[[session]]
name = "COde ğŸ’»"
path = "~/Code"

[[session]]
name = "NEovim config ï¯ "
path = "~/.config/nvim"
startup_command = "git status"

[[session]]
name = "POrtage config ğŸ§´"
path = "~/.pumpfiles/root/etc/portage/"

[[session]]
name = "PUmpndump ğŸ§´"
path = "~/.pumpfiles"
startup_command = "git status"

[[session]]
name = "SCripts ğŸ“œ "
path = "~/.scripts"

[[session]]
name = "SEsh config îµ” "
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "SOosh ó°£€ "
path = "~/.ssh/"
startup_command = "ssh gravity@clr"

[[session]]
name = "TMux config î¯ˆ "
path = "~/.tmux"
startup_command = "nvim ~/.tmux.conf"

[[session]]
name = "UPdate ó°š° " 
startup_command = "updatescript"

[[session]]
name = "LIttle cool website" 
path = "~/Code/coollittlewebsite"
startup_command = "~/.config/sesh/scripts/coollittlewebsite.sh"
